# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s75fgga676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado_projects/spain/spain.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/spain/spain.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/vivado_projects/spain/spain.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/vivado_projects/spain/spain.srcs/sources_1/new/delay.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/latch.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/Option_mode.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/RAM_WRAPPER.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/ad_count_ctrl.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/address_decoder.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/max_counter.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/mux.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/safe_latch.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/tristatebuff.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/signal_controller.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/ram_control.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/top_8254.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/tw_8254_cnt.vhd
  D:/vivado_projects/spain/spain.srcs/sources_1/new/pcfg_top.vhd
}
read_ip -quiet D:/vivado_projects/spain/spain.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files -all d:/vivado_projects/spain/spain.srcs/sources_1/ip/RAM/RAM_ooc.xdc]

read_ip -quiet D:/vivado_projects/spain/spain.srcs/sources_1/ip/xfft_0/xfft_0.xci
set_property used_in_implementation false [get_files -all d:/vivado_projects/spain/spain.srcs/sources_1/ip/xfft_0/xfft_0_ooc.xdc]

read_ip -quiet D:/vivado_projects/spain/spain.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property used_in_implementation false [get_files -all d:/vivado_projects/spain/spain.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc]

read_ip -quiet D:/vivado_projects/spain/spain.srcs/sources_1/ip/cordic_0/cordic_0.xci
set_property used_in_implementation false [get_files -all d:/vivado_projects/spain/spain.srcs/sources_1/ip/cordic_0/cordic_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_projects/spain/spain.srcs/constrs_1/imports/spain/pcfg2019_constraints.xdc
set_property used_in_implementation false [get_files D:/vivado_projects/spain/spain.srcs/constrs_1/imports/spain/pcfg2019_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top PCFG_TOP -part xc7s75fgga676-2 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef PCFG_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file PCFG_TOP_utilization_synth.rpt -pb PCFG_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
